### ISSUE TITLE
Submission loading state bouwen

### ISSUE THREAD

**Issue by Annevd** [Annevd/component-building-block#14]

**Comment by Annevd** [comment]
## Submission loading state

Na dat het form submitted is, en vóór dat de gebruiker de success state ziet, is er een loading state. Hier veranderd de cursor naar een laadrondje en krijgt de knop een pulse animation.
Dit doe ik door gebruik te maken van een dynamische variabele `isLoading` en een class op het form.

**De Javascript:**

```JS
  import { onMount } from "svelte";
    let isLoading = false;   // Een variabele die checkt of een form in een 'loading' state is
    onMount(() => {
        document.querySelector("form").addEventListener("submit", function(event) {
            event.preventDefault(); // Prevent the default form submission

            isLoading = true;    // Maak de 'isLoading' variabele true om aan te geven dat het form verwerkt wordt

            setTimeout(() => {
                const submitButton = document.querySelector("input[type='submit']");
                document.querySelector("input[type='submit']").value = "Verzenden gelukt!"; // Change the button text
                isLoading = false;  // Reset de 'isLoading' state na de gesimuleerd delay.

                submitButton.disabled = true; 
                submitButton.style.backgroundColor = "var(--main-color-green)";
                submitButton.style.color = "white";

                document.querySelector("form").reset();
            }, 2000);
        });
    });
```
**De HTML:**
```SVELTE
<form class="{isLoading ? 'loading-overlay' : ''}">
<!-- ls isLoading true is, krijgt het <form>-element de CSS class loading-overlay -->
<!-- Als isLoading false is, blijft de klasse leeg (''), en er wordt geen extra class toegevoegd.

 <input type="submit" value="Verzenden" aria-label="Verzend formulier" class="{isLoading ? 'loading' : ''}"/>
```

**De CSS:**
```CSS
input[type='submit'].loading { /* wanneer het form aan het laden is */
    animation: pulse 0.8s infinite;
    cursor: wait; 
}

.loading-overlay {
    position: relative;   /* Maakt het formulier relative voor het pseudo-element (::after). */
}

.loading-overlay::after { /* overlay waardoor de laadcursor over het hele formulier werkt */
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    cursor: wait;
    z-index: 10;
}
```
