### ISSUE TITLE
User preferences: reduced motion & prefers-color-scheme

### ISSUE THREAD

**Issue by Annevd** [Annevd/component-building-block#22]

**Comment by Annevd** [comment]
## Prefers-reduced-motion

Ik heb de code zo aangepast dat het formulier by default geen animatie heeft, en wanneer een gebruiker het niet heeft ingesteld de animatie automatisch wel op het formulier staat.

Dit heb ik gedaan door de code die met de animaties te maken heeft, in een media query te zetten.

```CSS
@media (prefers-reduced-motion: no-preference) {

    /* Plant valid animation */

    fieldset div:has(input:valid)::after {
        opacity: 1;
        scale: 1;
        transform: translateY(0);
    }

    fieldset div:has(input:focus)::after,
    fieldset div:has(input:focus:valid)::after {
        transform: translateY(20%);
        opacity:1;
        scale: 1;
        transition-delay: .3s;
    }

    /* Loading animation */

    input[type='submit'].loading {
        animation: pulse 0.8s infinite;
        cursor: wait; 
    }
}
```

Bij default heeft de plant svg een `opacity: 0;` en is die dus niet zichtbaar. Pas als de media query het toelaat, krijgt de svg een `opacity: 1;` en komt de animatie tevoorschijn.

Hetzelfde bij de button animatie. De animatie wordt alleen toegepast wanneer de media query, en dus de gebruiker het toestaat.

## Prefers-color-scheme

Ook heb ik een dark mode versie gemaakt, voor wanneer de gebruiker zijn systeeminstelling op dark of light heeft ingesteld.

Dit heb ik gedaan door een media query te schrijven wanneer ik de custom properties van de root verander.

```CSS
:root {
	--main-color-green: #4e7141;
	--main-color-beige: #f9e9c2;
	--main-color-orange: #ff8d06;
	--main-color-brown: #491b02;

	--card-color-orange: #ff9a41;
	--card-color-green: #3c593e;

	--text-color-white: #fff;
	--text-color-black: #000;
	--text-color-green: #3c593e;
	--invalid-color-red: #ff0000;
	--valid-color-green: #3c593e;

	--input-border-color: #B37400;

        /* etc. */
}

@media (prefers-color-scheme: dark) {
	:root {
		--main-color-beige: #1D1D1D;
		--text-color-green: var(--text-color-white);
		--valid-color-green: #3cc746 ;
		--input-border-color: none;
	}
}
```

Wanneer je systeeminstelling op dark staat, ziet het form er zo uit:

![image](https://github.com/user-attachments/assets/984d2a36-264c-4e83-8c89-af4ac3715294)

**Comment by Annevd** [comment]
## Prefers-reduced-motion

Ik heb de code zo aangepast dat het formulier by default geen animatie heeft, en wanneer een gebruiker het niet heeft ingesteld de animatie automatisch wel op het formulier staat.

Dit heb ik gedaan door de code die met de animaties te maken heeft, in een media query te zetten.

```CSS
@media (prefers-reduced-motion: no-preference) {

    /* Plant valid animation */

    fieldset div:has(input:valid)::after {
        opacity: 1;
        scale: 1;
        transform: translateY(0);
    }

    fieldset div:has(input:focus)::after,
    fieldset div:has(input:focus:valid)::after {
        transform: translateY(20%);
        opacity:1;
        scale: 1;
        transition-delay: .3s;
    }

    /* Loading animation */

    input[type='submit'].loading {
        animation: pulse 0.8s infinite;
        cursor: wait; 
    }
}
```

Bij default heeft de plant svg een `opacity: 0;` en is die dus niet zichtbaar. Pas als de media query het toelaat, krijgt de svg een `opacity: 1;` en komt de animatie tevoorschijn.

Hetzelfde bij de button animatie. De animatie wordt alleen toegepast wanneer de media query, en dus de gebruiker het toestaat.

**Comment by Annevd** [comment]
## Prefers-color-scheme

Ook heb ik een dark mode versie gemaakt, voor wanneer de gebruiker zijn systeeminstelling op dark of light heeft ingesteld.

Dit heb ik gedaan door een media query te schrijven wanneer ik de custom properties van de root verander.

```CSS
:root {
	--main-color-green: #4e7141;
	--main-color-beige: #f9e9c2;
	--main-color-orange: #ff8d06;
	--main-color-brown: #491b02;

	--card-color-orange: #ff9a41;
	--card-color-green: #3c593e;

	--text-color-white: #fff;
	--text-color-black: #000;
	--text-color-green: #3c593e;
	--invalid-color-red: #ff0000;
	--valid-color-green: #3c593e;

	--input-border-color: #B37400;

        /* etc. */
}

@media (prefers-color-scheme: dark) {
	:root {
		--main-color-beige: #1D1D1D;
		--text-color-green: var(--text-color-white);
		--valid-color-green: #3cc746 ;
		--input-border-color: none;
	}
}
```

Wanneer je systeeminstelling op dark staat, ziet het form er zo uit:

![image](https://github.com/user-attachments/assets/984d2a36-264c-4e83-8c89-af4ac3715294)

**Comment by Annevd** [comment]
## `light-dark()`

In een artikel van Medium kwam ik achter een nieuwe methode om een automatische dark mode te bouwen in CSS, namelijk met: `light-dark()`. Je kan daarmee heel makkelijk light/dark modes bepalen, op basis van de user prefered thema. Hiervoor hoef je geen `perfers-color-scheme` blocks meer te schrijven, maar kan je het simpelweg in de custom properties of elementen zelf zetten.

Omdat dit nog niet widely supported is heb ik het voor nu in een `@supports` gezet, zodat het nog altijd werkt ook wannneer deze methode niet supported is.

```CSS
@supports (color: light-dark(#fff, #0d0d0d)) {
	:root {
		--background-color: light-dark(#fff, #0d0d0d);
		--main-color-beige: light-dark(#f9e9c2, #212121);
		--text-color-green: light-dark(#3c593e, #fff);
		--text-color-brown: light-dark(#491b02, #fff);
		--valid-color-green: light-dark(#3c593e, #3cc746);
		--input-border-color: light-dark(#B37400, none);
	}
}
```

Je zet de waarde voor het lichte thema én het donkere thema achter dezelfde variabele.

### Bronnen
- [Medium artikel](https://medium.com/front-end-weekly/forget-javascript-achieve-dark-mode-effortlessly-with-brand-new-css-function-light-dark-2024-94981c61756b)
- [Mdn bron](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark)
