### ISSUE TITLE
agenda card component bouwen (met container query)

### ISSUE THREAD

**Issue by Annevd** [Annevd/component-building-block#23]
## Ontwerp

![image](https://github.com/user-attachments/assets/928caaf2-bec5-42f7-bc4a-1f58a9f452d9)

**Comment by Annevd** [comment]
## HTML

Ik ben begonnen met het maken van de HTML. Op de website ziet dat er zo uit:

<img width=150 src="https://github.com/user-attachments/assets/8c1e069c-d14d-459d-9dfa-56e705c65064">

De link is natuurlijk zonder CSS gewoon bruikbaar (PE).

**Zo ziet de (semantische) HTML code eruit:**

```HTML
<li>
    <div class="card-container"> <!-- Deze container is voor de container queries die ik later ga toepassen -->
        <picture>
            <img height=200 src="/src/lib/assets/workshop.webp" alt="">
        </picture>
        <div class="info-container">
            <h2>Stekjes maken</h2>
            <ul>
                <time datetime="13:00">13:00</time>
                <time datetime="2024-11-03">03/11/2024</time>
                <address>OBA Linnaeusstraat</address>
                <p>€10,-</p>
            </ul>
            <a href="/">Meld je aan <span><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 44 47"><path d="M40.492 18.788 8.942 1.034C4.944-1.218 0 1.673 0 6.262v34.704c0 4.537 4.842 7.433 8.84 5.285l31.549-16.948c4.167-2.239 4.225-8.195.103-10.515Z" fill="#fff"></path></svg></span></a>
        </div>
    </div>
</li>
```

**Comment by Annevd** [comment]
## CSS

**Zonder de container queries ziet het met CSS er zo uit:**

![image](https://github.com/user-attachments/assets/96959b4a-0e3b-4df0-8e2a-4dbc173043be)

De width schaalt automatisch mee dus mocht de container query niet supported zijn, is het nog steeds responsive.

**Comment by Annevd** [comment]
## CSS met container query

**Met de container query ziet het kaartje er zo uit bij smalle ruimte:**

![image](https://github.com/user-attachments/assets/76f0400b-dbe6-4494-a63a-5e64f8027862)

**En zo bij brede ruimte:**

![image](https://github.com/user-attachments/assets/635bcde6-b985-433c-9aee-3583eef74680)

**Op de `li` staat de container aangegeven, en de styling van de container query op de `.card-container`:**
```CSS
li {
    list-style: none;
    container-type: inline-size; /* Container query property */
    container-name: card;        /* Container query property */
}

@container card (width > 23rem) {
    .card-container {
        flex-direction: row; /* Default is column, bij meer ruimte veranderd het naar row */
        height: 14rem;
    }
    .card-container picture {
        width: 40%;
    }
    .info-container {
        gap: 0;
    }
    li picture {
        max-height: none;
    }
}
```
