### ISSUE TITLE
0% bij keyframe kan weg, want t is al default

### ISSUE THREAD

**Issue by Annevd** [Annevd/component-building-block#31]

**Comment by Annevd** [comment]
Opgelost door de default weg te halen:

```CSS

@keyframes pulse {
    50% {
        transform: scale(1.025);
    }
    100% {
        transform: scale(1);
    }
}
```
