### ISSUE TITLE
basic CSS toevoegen aan form

### ISSUE THREAD

**Issue by Annevd** [Annevd/component-building-block#4]
Denk aan laag 2 van PE. Zorg dat het er visueel goed uitziet.

**Comment by Annevd** [comment]
## CSS Styling

Aan de hand van mijn breakdownschets heb ik de meeste styling al op het form toegepast. Denk aan `display: flex;` en `flex-direction: column;` om de `fieldset`s en `input`s onder elkaar te zetten, de juiste kleuren en fonts op alle elementen, enige paddings en margins op inputs en buttons, etc.

Ook heb ik alvast een hover op de submit button gezet, en hebben de inputs een focus state. 

Ik heb mij gehouden aan mijn ontwerp die voldoen aan toegankelijkheids eisen. Denk aan box-shadow om de `input`s heen, en een achtergrondkleur op de button met een hoog genoeg contrast.

Dit is de CSS tot nu toe:

```CSS
form {
    display: flex;
    flex-direction: column;
    width: 100%;
    max-width: 35rem;
    gap: 1rem;
    color: var(--card-color-green);
    font-family: var(--sub-header-font);
}

fieldset {
    display: flex;
    flex-direction: column;
    border: none;
    gap: 0.5rem;
}

legend {
    padding: 0.5rem 0;
}

.questions {
    display: grid;
    grid-template-columns: 1.5rem auto;
    grid-template-areas:
    'radio1 question1'
    'radio2 question2';
}

.questions input:first-of-type {
    grid-area: radio1;
}

.questions input:nth-of-type(2) {
    grid-area: radio2;
}

.questions label:first-of-type {
    grid-area: question1;
}

.questions label:nth-of-type(2) {
    grid-area: question2;
}

input[type='radio']{
    width: 1.5rem;
    height: 1.5rem;
    accent-color: var(--main-color-green);
    cursor: pointer;
}

input[type='text'],
input[type='email'],
textarea {
    border: none;
    padding: 0.5rem;
    border-radius: var(--border-card);
    outline: none;
    box-shadow: 0px 2px 4px hsl(32 37% 39% / 1);
}

input[type='submit'] {
    border-radius: 2rem;
    border: none;
    cursor: pointer;
    padding: 0.5rem 1rem;
    margin: 0.5rem 0;
    font-size: 1rem;
    width: 8rem;
    background-color: var(--main-color-green);
    color: var(--text-color-white);
    transition: ease-in 0.1s;
}

input[type='submit']:hover {
    background-color: #4A8235;
}

input,
textarea {
    font-family: var(--paragraph-font);
}

::placeholder {
    color: #545454;
}

/* form focus styling */

input[type='text']:focus,
input[type='email']:focus,
textarea:focus {
    outline: 3px solid rgb(0, 0, 0, .6);
}
```
