### ISSUE TITLE
basic valid en invalid states toevoegen aan inputs

### ISSUE THREAD

**Issue by Annevd** [Annevd/component-building-block#5]
Denk aan laag 3 van PE.

**Comment by Annevd** [comment]
## Basic valid & Invalid states on inputs

Aan de hand van de `:valid` en `:user-invalid` pseudoclasses heb ik de basic valid en invalid states gebouwd waardoor de inputs een groene of rode styling krijgen wanneer een gebruiker een geldig of ongeldig antwoord heeft ingevuld.

```CSS
/* form focus valid  */

input[type='text']:valid,
input[type='email']:valid,
textarea:valid {
    outline: 2px solid var(--card-color-green);
    background: #E8FFE8;
}

/* form focus invalid */

input[type='text']:user-invalid,
input[type='email']:user-invalid,
textarea:user-invalid {
    outline: 2px solid var(--invalid-color-red);
}
```

Wanneer het form nog niet helemaal is ingevuld, of dingen nog niet valid zijn, kan je niet op de verzendknop klikken. Dit heb ik gedaan met `cursor: not-allowed`. Wanneer het gehele form geldig is, kleurt de knop weer groen, en is het klikbaar.

```CSS
/* default */
input[type='submit'] {
    border-radius: 2rem;
    border: none;
    cursor: not-allowed; /* niet klikbaar */
    padding: 0.5rem 1rem;
    margin: 0.5rem 0;
    font-size: 1rem;
    width: 8rem;
    background-color: #657266;
    color: var(--text-color-white);
    transition: ease-in 0.1s;
}
 /* wanneer alles geldig is ingevuld: */
form:valid input[type='submit'] {
    cursor: pointer; /* de knop is weer klikbaar */
    background: var(--main-color-green);
}
```

### Visuals

**Valid, Invalid & focus state:**

![image](https://github.com/user-attachments/assets/32fd891d-bdf5-4066-bdf2-9e1d99b26a21)

**Gehele form is valid:**

![image](https://github.com/user-attachments/assets/55087e9e-daaa-4171-be75-37919bf9e297)
